import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { Button, FormControl, IconButton, InputAdornment, InputLabel, OutlinedInput, TextField } from '@mui/material'
import { useState } from 'react'
import { Visibility, VisibilityOff } from '@mui/icons-material'
import InputInfomation from '@/components/InputInfomation'
import Back from '@/components/Back'
import { login } from '@/data/function'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [email,setEmail]=useState<string>("");
  const [password,setPassword]=useState<string>("");
  const func=():void=>login();
  return (
    <div 
      className='text-center'
      style={{
        height:"100vh",
        position:"relative"
      }}
    >
      <Head>
        <title>フロントとバックの連携練習</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Back/>
      <InputInfomation
        title="Login"
        email={setEmail}
        password={setPassword}
        clickfunction={func}
      />
    </div>
  )
}
